board:
  - nice_nano_v2

shield:
  - lapka_wellum36_left
  - lapka_wellum36_right
  - lapka_wellum36_dongle

include:
  - board: nice_nano_v2
    shield: lapka_wellum36_left
  - board: nice_nano_v2
    shield: lapka_wellum36_right
  - board: nice_nano_v2
    shield: lapka_wellum36_dongle
  - board: nice_nano_v2
    shield: lapka_wellum36_dongle_display
