# Turn off sleep for dongle (донгл питается от USB)
CONFIG_ZMK_SLEEP=n

# Включаем поддержку OLED дисплея и расширенный интерактивный экран
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Настройки батареи и проксирования заряда с половинок
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
