# ЖЕСТКО отключаем сон для донгла
CONFIG_ZMK_SLEEP=n

# Явно включаем USB для стабильной работы
CONFIG_ZMK_USB=y

# Включаем стандартный встроенный экран ZMK
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Настройки батареи и проксирования
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
